[features]
seeds = false
skip-lint = false

[programs.localnet]
nft_contest = "8wRhhgnw55z1QELi6wDoAnKbnYsU9X9U5kZnMQ12vopf"

[programs.devnet]
nft_contest = "8wRhhgnw55z1QELi6wDoAnKbnYsU9X9U5kZnMQ12vopf"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/masa/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
